export const constant = {
  title: "Any Time Shoot",
  search_hint: "Search...",
  location: "Gurugram",
  your_location: "Your Location",
  home: "Home",
  category: "Category",
  my_bookings: "My Bookings",
  profile: "Profile",
  wedding: "Wedding",
  maternity: "Maternity",
  pre_wedding: "Pre-Wedding",
  product: "Product",
  new_born: "New Born",
  right_arrow: "Right Arrow",
  logo: "Logo",
  top_booked_services: "Top Booked Categories",
  view_all: "View All",
  recommended_for_you: "Recommended For You",
  view_all_services: "View All Services",
  view_all_categories: "View All Categories",
  instant_bookings: "Instant Booking Pacakges",
  wedding_packages_near_you: "Wedding Packages Near You",
  upto_to: "Up to 70% off| Wedding, Prewedding Packages", 
  view_more: "View More",
  bestSeller_package: "Bestseller Packages",
  getStarted: "Get Started",
  specialOffer: "Special Offer",
  bestSeller: "Best Seller packages",
  similarPackage: "Similar packages",

  //AnyTimeShoot Constant Images
   onBoardTitle1: "Capture Life's Moments, Anytime, Anywhere",
   onBoardTitle2: "Instant Memories, Delivered",
   onBoardTitle3: "Your vision, our Expertise",
   onBoardDesc1:  " Book professional photographers in minutes. No more missed moments",
   onBoardDesc2:  "Your photos, delivered instantly. No more waiting",
   onBoardDesc3: "Browse amazing packages that will suit your style and taste",
   welcomeText: "Welcome To AnyTime",
   anyTime: "AnyTime",
   support: "Support",
   shoot: "Shoot",
   next: "Next",
   loginOrSignup: "Log In or Sign up",
   loginSecure: 'Securing your personal information is our priority.',
   phoneNumber: "Phone number",
   enterYourPhoneNo: "Enter your phone number",
   continue: "Continue",
   continueAs: "Continue as",
   guest: " Guest",
   verifyYourPhnNo: "Verify your phone number",
   enterTheCode: "Enter the code we’ve send to",
   resendOtp: "Resend Code",
   haventReceiveTheCode: "Haven't Received OTP Code?",
   verify: "Verify",
   success: "Success!",
   congrats: "Congratulations!",
   youhaveBeen: " You have been successfully authenticated",
   userName: "Username",
   enterYourEmail: "Enter Your Email",
   continueWithGoogle: "Continue With Google",
   skipForNow: "Skip for now",
   invalidOtpEntered: "Invalid OTP entered",
   clearAll: "Clear All",
   clear: "Clear",
   ok: "Ok",
   joinPartner: "Join as a Partner",
   settings: "Settings",
   itsEasyToGet: "It’s easy to get set up and start earning with AnyTime",
   addres: 'Address',
   whislist: 'Whislist',
   termsOfUse: "Terms of Use",
   cancellationPolicy: "Cancellation Policy",
   rateUs: "Rate Us",
   deleteAccount:"Delete Account",
   contactUs: "Contact Us",
   policy: 'Policy',
   deleteEverything: "Delete Everything",
   about: "About",
   ratings: "Ratings",
   products: "Products",
   profilePhoneNumber: "Phone Number",
   applyCoupon: "Apply Coupon",
   yourCartValue: "Your Cart Value",
   bestOffersForYou: "Best Offers for you",
   cashback: "Cashback",
   applied: "APPLIED",
   tapToApply: "TAP TO APPLY",
   enterYourCoupon: "Enter Your Coupon",
   get: "Get",
   upTo: "up to",
   onBookingDesc: "on booking photographers for minimum purchase of ₹2,45,000",
   typeMessageHere: "Type message here...",
   upcomingBookings: "Upcoming Bookings",
   completedBookings: "Completed Bookings",
   cancelledBookings: "Cancelled Bookings",
   upcomingDes: "Bookings which are in progress or to be started.",
   completedDes: "Bookings which are already completed.",
   cancelledDes: "Bookings which you cancelled.",
   viewAll: "View all",
   startShoot: "Start Shoot",
   otpVerification: "OTP verification for starting shoot",
   shootCompleted: 'Shoot Completed',
   photographerWillUploadPhotos: "Photographer will upload your photos",
   endingInProgress: 'Editing in Progress',
   willStartEditingSoon: 'Will start editing soon',
   workDelivered: 'Work Delivered',
   photosAreReady: 'Photos are ready (Links Attached)',
   getInvoice: "Get invoice",
   requestCancellation : "Request Cancellation ?",
   maternityShoot: "Maternity Shoot",
   studioExperts: "Studio Experts",
   ratingStarts: "4/5",
   yourBooking: "Your booking",
   totalBookingPrice: "Total Booking Price",
   bookingDetails: "Booking detail",
   count: "₹ 2,45,000",
   date: "17 Aug, 2025",
   editProfile: "Edit Profile",
   locationError: 'The service is not available in this location at the moment. We’re working hard to bring it to you –',
   comingSoon: ' Coming Soon',
   bookingNow: "Booking Now",
   cancelled: "Cancelled",
   cancel: "Cancel",
   cancelReason: 'You cancelled it on "DATE"',
   emptyText: "You haven't made any bookings yet. Start exploring our options and reserve your",
   spotNow: "spot Now",
   exlametry: "!!!",
   thankYouForYourPackage: "Thanks for creating the package, your package is your package is under review by",
   anyTimeShoot: " AnyTimeShoot",
   generateInvoice: "Generate Invoice",
   rateAndReview: "Rate & Review the booking",
   shootStarted:  "Shoot started", 
   successfully: "successfully",
   studioLocation: "Studio Location",
   help: "Help",
   location_caps: "Location",
   otherPackages: "Other Packages",
   someRandomAddress: "Some random address pincode",
   viewAllPackages: "View all other packages of photographer",
   packageRule: "Package Rule",
   aboutMe: "About Me",
   profileDetailSubText: "An experienced photographer with a passion for capturing life's most  memorable moments.Skilled in various photography styles, from portraits to events, ensuring each shot tells a unique story.",
   FAQ: "Frequently Asked Questions",
   averageRating: "Average Rating",
   bookNow: "Book Now",
   reviewPrice: "₹ 2,45,000",
   reviewRating: "4.5 and 1000+ reviews",
   readMore: "Read More",
   sheduledShoot: "Schedule Shoot",
   packageVerification: "Package Verification",
   packageSubVerification : "Thanks for creating the package, your package is under reviewed by AnyTime",
   pending: "Pending",
   pause: "Pause",
   live: "Live",
   addPackage: "Add Package",
   chooseCategory: "Choose Category",
   selectCategory: "Select category in which you want to create a package.",
   addDetails: "Add Details ",
   giveSome: "Give some details of your package",
   provideTheOverAll:"Provide the overall cost of the package .",
   packageName: "Package Name",
   packageDesc: "Package Description",
   nameYourPackage: "Name your package",
   addSomeBasic: "Add some basic description about package",
   shootIsStudio: "Shoot is in Studio?",
  yes: "Yes",
  no: "No",
  shootDuration: "Shoot Duration ",
  inHours: "(In Hours)",
  Eg: "E.g. 8",
  note: "Note:",
  twoNumber: "2. ",
  dont: "Don't",
  mentionNumberofDays: " mention number of days",
  shootHours: "1. If Shoot is of 3 days with 5 hours daily then mention 3 X 5 = ",
  hours: "15 hours",
  addStudioDetails: "Add Studio Details",
  giveSomeDetail: "Give some details about the studio",
  studioAddress: "Studio Address",
  enterAddress: "Enter Address",
  useMyCurrentLocation: " Use My Current Location",
  studioImages: "Studio Images",
  chooseAfile: "Choose a file or drag & drop it here",
  jpegOrPngFormats: "JPEG or PNG formats, up to 50 MB",
  facilitiesAvailable: "Facilities Available in Studio",
  changingRoom: "Changing Room",
  washRoom: "Wash Room",
  airConditioning: "Air Conditioning",
  freeParking: "Free Parking",
  makeupArtisit: "Makeup Artist",
  backdrops: "Backdrops",
  soundproofArea: "Soundproof Area",
  props: "Props",
  wardrobe: "Wardrobe",
  facilitiesInclude: "Facilities included in the package",
  uploaded: "Uploaded",

//PackageDetails
  includeInPackage: "Includes in package",
  deliveryDetails: "Delivery Details",
  descDelivery: "Describe the detailed schedule for your deliverables .",
  rawData: "Raw Data",
  deliveryMode: "Delivery Mode",
  deliveyTime: "Delivery Time",
  selectMode: "select mode",
  numberOfDays: "Number of days after shoot",
  editedData: "Edited Data *",
  offline: "Offline",
  cloudSharing: "Cloud Sharing",
  whenYouWillGetDeliverables: "When you will get deliverables",
  timelineAftershoot: 'Timeline after shoot',

  additionInformation: "Additional Information",
  chooseCancellationPolicy: "Choose Cancellation Policy",
  pickAcancellationPolicy: "Pick a cancellation policy",
  locationWhereYouAccepting: "Location where you accept booking",
  policy1: "Policy 1",
  policy2: "Policy 2",
  policy3: "Policy 3",
  policy4: "Policy 4",
  policy5: "Policy 5",
  gurugam: "Gurugam",
  pricingDetails: "Pricing Details",
  provideTheOverall: "Provide the overall cost of the package",
  enterPrice: "Enter Price *",
  enterPricingValue: "Enter Pricing Value",
  pleaseNote: "Please Note:",
  pricingDetail1: "1. Our Focus is provide end to end services to our clients, we encourage to Add All inclusive prices for your Package.",
  pricingDetail2: "2. Please Note on Each booking we will charge 3% Commission on the price you will mention here.",
  pricingDetail3: "3. Please Note while creating any Package include all the expenses.",
  addRules: "Add Rules / Terms & Conditions ",
  addAnyExtra: "Add any extra terms which customer should keep in mind for the shoot .",
  rulesText: "Shoot will be done in the mentioned hours only and extra hours will charge extra.",
  save: "Save",
  extraPerks: "Extra Perks",
  extraPerksIncluded:"Extra  perks included in this package",
  deliverSomethingExtra: "Deliver something extra to win over your customer.",
  yourPackageWillBe: "Your package will give:",
  addExtraPerks: "Add extra  perks which you are giving in package:",
  fastPostProduction: "Fast Post Production",
  wardrobes: "Wardobes",
  doorStepShoot: "Door Step Shoot",
  postingTips: "Posing Tips",
  scripting: "Scripting",
  onlineSharing: "Online Sharing",
  freeEInvites: "Free E-Invites",
  other: "Other",
  addSampleForPackage: "Add Sample for package",
  provideSample: "Provide sample image/videos for the shoot and deliverables .",
  thumbnailImage:"Thumbnail Image *",
  sampleVideo: "Sample Video",
  sampleImages: "Sample Images",
  deliverable: "Deliverable",
  quantity: "Qunatity",
  give: "* Give",
  minimum: " minimum",
  numberOfImage: " number of ",
  nameDeliverable: "Name Deliverable",
  numberOfTheDeliverable: "Number of the Deliverable",
  mentionDetails:"Mention details of what will you deliver after the shoot .",

  rawImages: "Raw Images",
  editedImages: "Edited Images",
  rawVideo: "Raw Video",
  editedVideos: "Edited Videos",
  reels: "Reels",
  videoTeaser: "Video Teaser",
  highlightVideo: "Highlight Video",
  album: "Album",
  photoFrame: "Photo Frame",
  other10: "10. Other",
  images: "images",

  //Partners Onboarding 
  youCanEarnWith :'You can earn with',
  estimateTime: "Estimate your earning based on location",
  searchText: "Sector-23, Ghaziabad",
  searchCategory: "Maternity Shoot",
  describePhotography: "Describe Your Photography Business",
  uploadDocument:  "Upload your Documents ",
  enterBankDetails: "Enter Your Bank Details" ,
  quickReviewBefore: "Quick review before submit !",
  pleaseEnterYourInfo: "Please enter your information in the following fields.",
  uploadingYourDocuments: "Uploading your documents will help us to verify your profile .",
  forSmoothAndHassle:  "For smooth and hassle free pay outs , enter your bank details .",
  reviewTheInfo: "Review the information you’ve providede before submitting .",
  partner: "Partner",
  yourArePartner: "You are a " ,
  yourArePartner2: " Now !!",
  createFirstPackage: "Create your first package to start accepting bookings on AnyTimeShoot",
  doItLater: "I’ll do it later",
  getOTP: "Get OTP via",
  otpMsg: "Please enter the mode via you will get the OTP.",
  verifyMsg: "Please enter 6 digit OTP received in your ",
  giveSomeMoreDetails: "Give some more details of your package .",
  bookingStats: "Booking Stats",
  totalBooking: "Total Booking",
  lastMonth: "+30 from last month",
  cameraGears: "Camera Gears",
  videoCameraGears: "Video Camera Gears",
  mobilePhoneCamera: "Mobile Phone Camera",
  drone: "Drone",
  droneDetail: "All the drone model that will be used for the  shoot .",
  lightsReflectors :"Lights / Reflectors",
  lightsReflectorDetail: "All the lights/reflectors that will be used for the  shoot .",
  otherAccessories: "Other Accessories",
  otherAccessoriesDetail: "All the other accessories that will be used for the  shoot .",
  softwareDetails: "Software Details",
  softwareUsedDetail: "All the software that will be used while and after  the  shoot .",
  gearsAndSoftwares: "Gears and Softwares",
  mobilePhoneDetail: "All the Mobile  that will be used for the Camera shoot .",
  mentionDevies: "Mention devices and software which you will use.",
  allTheDevies: "All the cameras that will be used for the video shoot .",
  nameTheModel: "Name the model",
  model: "Model",
  modelName: " Modal Name ",
  nameOfTheCamera: "name of the Camera",
  brandName: "Brand Name",
  enterModelOfCamera: "Enter name of the camera",
  enterModelOfCompany:"Enter name of the company",
  softwareUsed: "Software Used",
  Accessories: "Accessories",
  ledLights: "Led Lights",
  umberllaLights: "Umbrella Lights",
  flashes: "Flashes",
  filters: "Filters",
  reflectors: "Reflectors",
  diffusers: "Diffusers",
  software: "Software",
  enterSoftwareName: "Enter Software Name",
  pricing: "Pricing",
  rating: "Rating",
  filterDes: "Add Filter for personalized results",
  apply: "Apply",
  clearFilters: "Clear Filters",
  above4: "4 & above",
  above3: "4 & above",
  above: "above",
 chooseYourBookingType: "Choose your Booking Type",
 selectYourPrefreed: "Select your preferred booking method that suits you",
 learnMoreAbout: "Learn More About",
 createPackage: "Crate Package",
 instant: "Instant",
 instantBooking: "Instant Booking",
 forLastMinutephotography: "For last-minute photography booking requests",
 birthday: "Birthday",
 preWedding: "Pre Wedding",
 food: "Food",
 haldi: "Haldi",
 portfolio: "Portfolio",
 handleFeedback: "Handle Feedback",
 respectPrivacy: 'Respect Privacy',
 followSafety: "Follow Safety Regulations",
 professionalConduct: "Professional Conduct",
 notifyIssues: "Notify Issues",
 goodServiceQuality: "Good Service quality",
 arriveOnTime: "Arrive on Time",
 prepareEquipement: "Prepare Equipment",
 confirmAvailabilityAnd: "Confirm availability",
 socialMedia: "Social Media",
 termsFor: "Terms for",
 confirmDesc: "Confirm availability and be ready to accept instant bookings without delays.",
 prepareEquipmentDesc: "Ensure all equipment is prepared and functional for same-day shoots.",
 arriveOnTimeDesc: "Arrive at the client's location promptly as scheduled.",
 goodServiceQualityDesc: "Provide the same level of service quality for instant bookings as regular ones.",
 notifyIssuesDesc: "Notify the client immediately if any unforeseen issues arise affecting the booking.",
 professionalDesc: "Maintain professional conduct and appearance during all instant bookings.",
 pricingDesc: "Abide by the agreed-upon pricing for instant bookings.",
 followSafetyDesc: "Follow all legal and safety regulations during the shoot.",
 respectDesc: "Respect the client's privacy and property while on-site.",
 handleFeedbackDesc: "Handle any client feedback or complaints professionally and promptly.",


  tripod: "Tripod",
  gimbal: "Gimpal",
  cranes: "Cranes",
  jibs: "Jibs",
  monopod: "Monopod",
  backDrop: "Backdrop",
  ledScreen: "Led Screen",

  adobephotoshop: "Adobe Photoshop",
  adobeLightroom: "Adobe Lightroom",
  canva: "Canva",
  adobePremierPro: "Adobe Premier Pro",
  adobeAfterEffects: "Adobe After Effects",
  davinciResolve: "Davinci Resolve",

  // Devices:

  canon: "Canon",
  nikon: "Nikon",
  sony: "Sony",
  fujiFlim: "FujiFilm",
  panasonic: "Panasonic",
  olympus: "Olympus",
  gopro: "Go-Pro",
  leica: "Leica",
  kodak: "Kodak",
  
  
}