export const constant = {
  title: "Any Time Shoot",
  search_hint: "Search...",
  location: "Gurugram",
  your_location: "Your Location",
  home: "Home",
  category: "Category",
  my_bookings: "My Bookings",
  profile: "Profile",
  wedding: "Wedding",
  maternity: "Maternity",
  pre_wedding: "Pre-Wedding",
  product: "Product",
  new_born: "New Born",
  right_arrow: "Right Arrow",
  logo: "Logo",
  top_booked_services: "Top Booked Categories",
  view_all: "View All",
  recommended_for_you: "Recommended For You",
  view_all_services: "View All Services",
  view_all_categories: "View All Categories",
  instant_bookings: "Instant Booking Pacakges",
  wedding_packages_near_you: "Wedding Packages Near You",
  upto_to: "Up to 70% off| Wedding, Prewedding Packages", 
  view_more: "View More",
  bestSeller_package: "Bestseller Packages",
  getStarted: "Get Started",
  specialOffer: "Special Offer",
  bestSeller: "Best Seller packages",

  //AnyTimeShoot Constant Images
   onBoardTitle1: "Capture Life's Moments, Anytime, Anywhere",
   onBoardTitle2: "Instant Memories, Delivered",
   onBoardTitle3: "Your vision, our Expertise",
   onBoardDesc1:  " Book professional photographers in minutes. No more missed moments",
   onBoardDesc2:  "Your photos, delivered instantly. No more waiting",
   onBoardDesc3: "Browse amazing packages that will suit your style and taste",
   welcomeText: "Welcome To AnyTime",
   anyTime: "AnyTime",
   support: "Support",
   shoot: "Shoot",
   next: "Next",
   loginOrSignup: "Log In or Sign up",
   loginSecure: 'Securing your personal information is our priority.',
   phoneNumber: "Phone number",
   enterYourPhoneNo: "Enter your phone number",
   continue: "Continue",
   continueAs: "Continue as",
   guest: " Guest",
   verifyYourPhnNo: "Verify your phone number",
   enterTheCode: "Enter the code we’ve send to",
   resendOtp: "Resend Code",
   haventReceiveTheCode: "Haven't Received OTP Code?",
   verify: "Verify",
   success: "Success!",
   congrats: "Congratulations!",
   youhaveBeen: " You have been successfully authenticated",
   userName: "Username",
   enterYourEmail: "Enter Your Email",
   continueWithGoogle: "Continue With Google",
   skipForNow: "Skip for now",
   invalidOtpEntered: "Invalid OTP entered",
   clearAll: "Clear All",
   clear: "Clear",
   ok: "Ok",
   joinPartner: "Join as a Partner",
   settings: "Settings",
   itsEasyToGet: "It’s easy to get set up and start earning with AnyTime",
   addres: 'Address',
   whislist: 'Whislist',
   termsOfUse: "Terms of Use",
   cancellationPolicy: "Cancellation Policy",
   rateUs: "Rate Us",
   deleteAccount:"Delete Account",
   contactUs: "Contact Us",
   policy: 'Policy',
   deleteEverything: "Delete Everything",
   about: "About",
   ratings: "Ratings",
   products: "Products",
   profilePhoneNumber: "Phone Number",
   applyCoupon: "Apply Coupon",
   yourCartValue: "Your Cart Value",
   bestOffersForYou: "Best Offers for you",
   cashback: "Cashback",
   applied: "APPLIED",
   tapToApply: "TAP TO APPLY",
   enterYourCoupon: "Enter Your Coupon",
   get: "Get",
   upTo: "up to",
   onBookingDesc: "on booking photographers for minimum purchase of ₹2,45,000",
   typeMessageHere: "Type message here...",
   upcomingBookings: "Upcoming Bookings",
   completedBookings: "Completed Bookings",
   cancelledBookings: "Cancelled Bookings",
   upcomingDes: "Bookings which are in progress or to be started.",
   completedDes: "Bookings which are already completed.",
   cancelledDes: "Bookings which you cancelled.",
   viewAll: "View all",
   startShoot: "Start Shoot",
   otpVerification: "OTP verification for starting shoot",
   shootCompleted: 'Shoot Completed',
   photographerWillUploadPhotos: "Photographer will upload your photos",
   endingInProgress: 'Editing in Progress',
   willStartEditingSoon: 'Will start editing soon',
   workDelivered: 'Work Delivered',
   photosAreReady: 'Photos are ready (Links Attached)',
   getInvoice: "Get invoice",
   requestCancellation : "Request Cancellation ?",
   maternityShoot: "Maternity Shoot",
   studioExperts: "Studio Experts",
   ratingStarts: "4/5",
   yourBooking: "Your booking",
   totalBookingPrice: "Total Booking Price",
   bookingDetails: "Booking detail",
   count: "₹ 2,45,000",
   date: "17 Aug, 2025",
   editProfile: "Edit Profile",
   locationError: 'The service is not available in this location at the moment. We’re working hard to bring it to you –',
   comingSoon: ' Coming Soon',
   bookingNow: "Booking Now",
   cancelled: "Cancelled",
   cancel: "Cancel",
   cancelReason: 'You cancelled it on "DATE"',
   emptyText: "You haven't made any bookings yet. Start exploring our options and reserve your",
   spotNow: "spot Now",
   exlametry: "!!!",
   thankYouForYourPackage: "Thanks for creating the package, your package is your package is under review by",
   anyTimeShoot: " AnyTimeShoot",
   generateInvoice: "Generate Invoice",
   rateAndReview: "Rate & Review the booking",
   shootStarted:  "Shoot started", 
   successfully: "successfully",
   studioLocation: "Studio Location",
   help: "Help",
   location_caps: "Location",
   otherPackages: "Other Packages",
   someRandomAddress: "Some random address pincode",
   viewAllPackages: "View all other packages of photographer",
   packageRule: "Package Rule",
   aboutMe: "About Me",
   profileDetailSubText: "An experienced photographer with a passion for capturing life's most  memorable moments.Skilled in various photography styles, from portraits to events, ensuring each shot tells a unique story.",
   FAQ: "Frequently Asked Questions",
   averageRating: "Average Rating",
   bookNow: "Book Now",
   reviewPrice: "₹ 2,45,000",
   reviewRating: "4.5 and 1000+ reviews",
   readMore: "Read More",
   sheduledShoot: "Schedule Shoot",
   packageVerification: "Package Verification",
   packageSubVerification : "Thanks for creating the package, your package is under reviewed by AnyTime",
   pending: "Pending",
   pause: "Pause",
   live: "Live",
   addPackage: "Add Package",
   chooseCategory: "Choose Category",
   selectCategory: "Select category in which you want to create a package.",
   addDetails: "Add Details ",
   giveSome: "Give some details of your package",
   packageName: "Package Name",
   packageDesc: "Package Description",
   nameYourPackage: "Name your package",
   addSomeBasic: "Add some basic description about package",
   shootIsStudio: "Shoot is in Studio?",
  yes: "Yes",
  no: "No",
  shootDuration: "Shoot Duration ",
  inHours: "(In Hours)",
  Eg: "E.g. 8",
  note: "Note:",
  twoNumber: "2. ",
  dont: "Don't",
  mentionNumberofDays: " mention number of days",
  shootHours: "1. If Shoot is of 3 days with 5 hours daily then mention 3 X 5 = ",
  hours: "15 hours",
  addStudioDetails: "Add Studio Details",
  giveSomeDetail: "Give some details about the studio",
  studioAddress: "Studio Address",
  enterAddress: "Enter Address",
  useMyCurrentLocation: " Use My Current Location",
  studioImages: "Studio Images",
  chooseAfile: "Choose a file or drag & drop it here",
  jpegOrPngFormats: "JPEG or PNG formats, up to 50 MB",
  facilitiesAvailable: "Facilities Available in Studio",
  changingRoom: "Changing Room",
  washRoom: "Wash Room",
  airConditioning: "Air Conditioning",
  freeParking: "Free Parking",
  makeupArtisit: "Makeup Artist",
  backdrops: "Backdrops",
  soundproofArea: "Soundproof Area",
  props: "Props",
  wardrobe: "Wardrobe",
  facilitiesInclude: "Facilities included in the package",
  uploaded: "Uploaded",


  includeInPackage: "Includes in package",
  deliveryDetails: "Delivery Details",
  descDelivery: "Describe the detailed schedule for your deliverables .",
  rawData: "Raw Data",
  deliveryMode: "Delivery Mode",
  deliveyTime: "Delivery Time",
  selectMode: "select mode",
  numberOfDays: "Number of days after shoot",
  editedData: "Edited Data *",
  offline: "Offline",
  cloudSharing: "Cloud Sharing",

  additionInformation: "Additional Information",
  chooseCancellationPolicy: "Choose Cancellation Policy",
  pickAcancellationPolicy: "Pick a cancellation policy",
  locationWhereYouAccepting: "Location where you accept booking",
  policy1: "Policy 1",
  gurugam: "Gurugam",
  pricingDetails: "Pricing Details",
  provideTheOverall: "Provide the overall cost of the package",
  enterPrice: "Enter Price *",
  enterPricingValue: "Enter Pricing Value",
  pleaseNote: "Please Note:",
  pricingDetail1: "1. Our Focus is provide end to end services to our clients, we encourage to Add All inclusive prices for your Package.",
  pricingDetail2: "2. Please Note on Each booking we will charge 3% Commission on the price you will mention here.",
  pricingDetail3: "3. Please Note while creating any Package include all the expenses.",
  addRules: "Add Rules / Terms & Conditions ",
  addAnyExtra: "Add any extra terms which customer should keep in mind for the shoot .",
  rulesText: "Shoot will be done in the mentioned hours only and extra hours will charge extra.",
  save: "Save",
  extraPerks: "Extra Perks",
  deliverSomethingExtra: "Deliver something extra to win over your customer.",
  yourPackageWillBe: "Your package will give:",
  addExtraPerks: "Add extra  perks which you are giving in package:",
  fastPostProduction: "Fast Post Production",
  wardrobes: "Wardobes",
  doorStepShoot: "Door Step Shoot",
  postingTips: "Posing Tips",
  scripting: "Scripting",
  onlineSharing: "Online Sharing",
  freeEInvites: "Free E-Invites",
  other: "Other",
  addSampleForPackage: "Add Sample for package",
  provideSample: "Provide sample image/videos for the shoot and deliverables .",
  thumbnailImage:"Thumbnail Image *",
  sampleVideo: "Sample Video",
  sampleImages: "Sample Images",
  deliverable: "Deliverable",
  quantity: "Qunatity",
  give: "* Give",
  minimum: " minimum",
  numberOfImage: " number of images",
  nameDeliverable: "Name Deliverable",
  numberOfTheDeliverable: "Number of the Deliverable",
  mentionDetails:"Mention details of what will you deliver after the shoot .",

  rawImages: "Raw Images",
  editedImages: "Edited Images",
  rawVideo: "Raw Video",
  editedVideos: "Edited Videos",
  reels: "Reels",
  videoTeaser: "Video Teaser",
  highlightVideo: "Highlight Video",
  album: "Album",
  photoFrame: "Photo Frame",
  other10: "10. Other",
  images: "images",

}