export const icons = {
  bellIcon : require('../../assets/icons/bell.png'),
  locationIcon : require('../../assets/icons/cart.png'),
  cartIcon: require('../../assets/icons/cart.png'),
  heartIcon: require('../../assets/icons/heart.png'),
  nextArrowIcon: require('../../assets/icons/nextArrow.png'),
  homeActiveIcon: require('../../assets/icons/home_active.png'),
  homeInactiveIcon: require('../../assets/icons/home_inactive.png'),
  messageActiveIcon: require('../../assets/icons/message_active.png'),
  messageInactiveIcon: require('../../assets/icons/message_inactive.png'),
  myBookingsActiveIcon: require('../../assets/icons/booking_active.png'), 
  myBookingsInactiveIcon: require('../../assets/icons/booking_inactive.png'),
  profileActiveIcon: require('../../assets/icons/profile_active.png'),
  profileInactiveIcon: require('../../assets/icons/profile_inactive.png'),
  closeIcon: require('../../assets/icons/close.png'),
  editIcon: require('../../assets/icons/edit.png'),
   filterIcon: require('../../assets/icons/filter.png'),
  phoneIcon : require('../../assets/icons/phone.png'),
  locationAppColorIcon : require('../../assets/icons/location.png'),
  heartAppColorIcon : require('../../assets/icons/heart_appColor.png'),
  shareIcon : require('../../assets/icons/share.png'),
  humanIcon : require('../../assets/icons/human.png'),
  contact:  require('../../assets/icons/contact.png'),
  starIcon : require('../../assets/icons/star.png'),
  cancellationIcon : require('../../assets/icons/cancellation.png'),
  deleteAccountIcon : require('../../assets/icons/delete.png'),
  sendIcon : require('../../assets/icons/sendIcon.png'),
  addImageIcon : require('../../assets/icons/addImageIcon.png'),
  datePicker:   require('../../assets/icons/datepicker.png'),
  priceIcone: require('../../assets/icons/price.png'),
  startShoot:   require('../../assets/icons/start_shoot.png'),
  editingIcon: require('../../assets/icons/editing.png'),
  workDeliveredIcon: require('../../assets/icons/work_delivered.png'),
  shootCompletedIcon: require('../../assets/icons/shoot_complete.png'),
  verifyIcon: require('../../assets/icons/verify.png'),
  timerIcon: require('../../assets/icons/timer.png'),
  rawDataIcon: require('../../assets/icons/raw_data.png'),
  editRawDataIcon: require('../../assets/icons/edit_raw_data.png'),
  backArrowIcon: require('../../assets/icons/back_arrow.png'),
  ovalLocationIcon: require('../../assets/icons/oval_location.png'),
  chatIcon: require('../../assets/icons/chat.png'),
  bookmarkIcon: require('../../assets/icons/bookmarkIcon.png'),
  closeFilterIcon: require('../../assets/icons/ic_close_icon.png')
}