export const images = {
  home: require('../../assets/images/home.png'),
  category: require('../../assets/images/category.png'),
  myBookings: require('../../assets/images/myBookings.png'),
  profile: require('../../assets/images/Profile.png'),
  wedding: require('../../assets/images/wedding.jpg'),
  maternity: require('../../assets/images/maternity.jpeg'),
  preWedding: require('../../assets/images/preWedding.jpg'),
  product: require('../../assets/images/product.jpeg'),
  newBorn: require('../../assets/images/newBorn.jpeg'),
  rightArrow: require('../../assets/images/right-arrow.png'),
  logo: require('../../assets/images/logo.png'),
  notification: require('../../assets/images/notification.png'),
  message: require('../../assets/images/message.png'),
  search: require('../../assets/images/search.png'),
  heart: require('../../assets/images/heart.png'),
  location: require('../../assets/images/location.png'),
  banner: require('../../assets/images/banner.jpg'),
  filledStar: require('../../assets/images/filled_star.png'),
  emptyStar: require('../../assets/images/empty_star.png'),
  verify: require('../../assets/images/verify.png'),
  liked: require('../../assets/images/liked.png'),
}