export const images = {
  home: require('../../assets/images/home.png'),
  messageIcon: require('../../assets/images/messageIcon.png'),
  myBookings: require('../../assets/images/myBookings.png'),
  profile: require('../../assets/images/profile.png'),
  wedding: require('../../assets/images/wedding.jpg'),
  maternity: require('../../assets/images/maternity.jpeg'),
  preWedding: require('../../assets/images/preWedding.jpg'),
  product: require('../../assets/images/product.jpeg'),
  newBorn: require('../../assets/images/newBorn.jpeg'),
  rightArrow: require('../../assets/images/right-arrow.png'),
  logo: require('../../assets/images/logo.png'),
  notification: require('../../assets/images/notification.png'),
  message: require('../../assets/images/message.png'),
  search: require('../../assets/images/search.png'),
  heart: require('../../assets/images/heart.png'),
  location: require('../../assets/images/location.png'),
  banner: require('../../assets/images/banner.jpg'),
  filledStar: require('../../assets/images/filled_star.png'),
  emptyStar: require('../../assets/images/empty_star.png'),
  verify: require('../../assets/images/verified.png'),
  liked: require('../../assets/images/liked.png'),
  camProduct : require('../../assets/images/camProduct.png'),
  orangeProduct : require('../../assets/images/orangeProduct.jpeg'),
  stylishMan: require('../../assets/images/stylishMan.jpg'),
  coupleMaternity: require('../../assets/images/coupleMaternity.jpeg'),
  lawer: require('../../assets/images/lawer.jpeg'),
  familyMaternity: require('../../assets/images/familyMaternity.jpeg'),
  banner2: require('../../assets/images/banner2.png'),
  banner3: require('../../assets/images/banner3.jpg'),
  banner4: require('../../assets/images/banner4.jpeg'),
  banner5: require('../../assets/images/banner5.png'),
  banner6: require('../../assets/images/banner6.jpg'),
  rightBgArrow: require('../../assets/images/arrow-right.png'),

  //AnyTimeShoot Constant Images
  onBoardBanner: require('../../assets/images/onBoardBanner.png'),
  onBoardBanner2: require('../../assets/images/onBoardBanner2.png'),
  onBoardBanner3: require('../../assets/images/onBoardBanner3.png'),
  skipArrow: require('../../assets/images/Vector.png'),
  loginCam: require('../../assets/images/loginCam.png'),
  checkIcon: require('../../assets/images/checkIcon.png'),
  mobileVerifyTick: require('../../assets/images/mobileVerify.png'),
  otpBlankBg: require('../../assets/images/otpBlankBg.png'),
  otpSuccessBg: require('../../assets/images/otpSuccessBg.png'),
  otpFilledBg: require('../../assets/images/otpFilledBg.png'),
  signInBg: require('../../assets/images/signInBg.png'),
  googleIcon: require('../../assets/images/google.png'),
  profileTopImage: require('../../assets/images/profileTopImg.png'),
  profileImage: require('../../assets/images/profileImage.png'),
  rightAppNextArrow: require('../../assets/images/right_app_arrow.png'),
  backIcon: require('../../assets/images/back.png'),
  locationIcon: require('../../assets/images/locationIcon.png'),
  phoneIcon: require('../../assets/images/phoneIcon.png'),
  whislistIcon: require('../../assets/images/whislistIcon.png'),
  termsIcon: require('../../assets/images/termsIcon.png'),
  canPolicyIcon: require('../../assets/images/canPolicyIcon.png'),
  rateUsIcon: require('../../assets/images/rateUsIcon.png'),
  deleteAccountIcon: require('../../assets/images/deleteAccountIcon.png'),
  contactUsIcon: require('../../assets/images/contactUsIcon.png'),
  editProfileIcon: require('../../assets/images/editProfileIcon.png'),
  appliedCouponIcon: require('../../assets/images/appliedCouponIcon.png'),
  messageCenterImage: require('../../assets/images/messageCenterImage.png'),
  sendIcon: require('../../assets/images/sendIcon.png'),
  addIcon: require('../../assets/images/addIcon.png'),
  upcomingBooking: require('../../assets/images/upcomingBooking.png'),
  cancelBooking: require('../../assets/images/cancelBooking.png'),
  completedBooking: require('../../assets/images/completedBooking16.png'),
  shareIcon: require('../../assets/images/shareIcon.png'),
};

